In [124]:
import pandas as pd
import re
import nltk
import pickle

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Download NLTK resources (run once)
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to C:\Users\PONNA
[nltk_data]     THRIVENI\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\PONNA
[nltk_data]     THRIVENI\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\PONNA
[nltk_data]     THRIVENI\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [125]:
df = pd.read_csv("resume.csv")   # change file name if needed
df

,content,annotation,extras
0,Abhishek Jha\nApplication Development Associat...,"[{'label': ['Skills'], 'points': [{'start': 12...",NaN
1,Afreen Jamadar\nActive member of IIIT Committe...,"[{'label': ['Email Address'], 'points': [{'sta...",NaN
2,"Akhil Yadav Polemaina\nHyderabad, Telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37...",NaN
3,Alok Khandai\nOperational Analyst (SQL DBA) En...,"[{'label': ['Skills'], 'points': [{'start': 80...",NaN
4,Ananya Chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20...",NaN
...,...,...,...
215,"Mansi Thanki\nStudent\n\nJamnagar, Gujarat - E...","[{'label': ['College Name'], 'points': [{'star...",NaN
216,Anil Kumar\nMicrosoft Azure (Basic Management)...,"[{'label': ['Location'], 'points': [{'start': ...",NaN
217,Siddharth Choudhary\nMicrosoft Office Suite - ...,"[{'label': ['Skills'], 'points': [{'start': 78...",NaN
218,Valarmathi Dhandapani\nInvestment Banking Oper...,"[{'label': ['Skills'], 'points': [{'start': 92...",NaN
219,Pradeep Kumar\nSecurity Analyst in Infosys - C...,"[{'label': ['Skills'], 'points': [{'start': 58...",NaN

In [154]:
import pandas as pd

df = pd.read_csv("resume.csv")
print(df.columns)




df.columns = df.columns.str.strip().str.lower()
print(df.head())

Index(['content', 'annotation', 'extras'], dtype='object')
                                             content  \
0  Abhishek Jha\nApplication Development Associat...
1  Afreen Jamadar\nActive member of IIIT Committe...
2  Akhil Yadav Polemaina\nHyderabad, Telangana - ...
3  Alok Khandai\nOperational Analyst (SQL DBA) En...
4  Ananya Chavan\nlecturer - oracle tutorials\n\n...

                                          annotation  extras
0  [{'label': ['Skills'], 'points': [{'start': 12...     NaN
1  [{'label': ['Email Address'], 'points': [{'sta...     NaN
2  [{'label': ['Skills'], 'points': [{'start': 37...     NaN
3  [{'label': ['Skills'], 'points': [{'start': 80...     NaN
4  [{'label': ['Degree'], 'points': [{'start': 20...     NaN

In [155]:
df.head()

,content,annotation,extras
0,Abhishek Jha\nApplication Development Associat...,"[{'label': ['Skills'], 'points': [{'start': 12...",NaN
1,Afreen Jamadar\nActive member of IIIT Committe...,"[{'label': ['Email Address'], 'points': [{'sta...",NaN
2,"Akhil Yadav Polemaina\nHyderabad, Telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37...",NaN
3,Alok Khandai\nOperational Analyst (SQL DBA) En...,"[{'label': ['Skills'], 'points': [{'start': 80...",NaN
4,Ananya Chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20...",NaN

In [156]:
df.tail()

,content,annotation,extras
215,"Mansi Thanki\nStudent\n\nJamnagar, Gujarat - E...","[{'label': ['College Name'], 'points': [{'star...",NaN
216,Anil Kumar\nMicrosoft Azure (Basic Management)...,"[{'label': ['Location'], 'points': [{'start': ...",NaN
217,Siddharth Choudhary\nMicrosoft Office Suite - ...,"[{'label': ['Skills'], 'points': [{'start': 78...",NaN
218,Valarmathi Dhandapani\nInvestment Banking Oper...,"[{'label': ['Skills'], 'points': [{'start': 92...",NaN
219,Pradeep Kumar\nSecurity Analyst in Infosys - C...,"[{'label': ['Skills'], 'points': [{'start': 58...",NaN

In [157]:
df.info

<bound method DataFrame.info of                                                content  \
0    Abhishek Jha\nApplication Development Associat...
1    Afreen Jamadar\nActive member of IIIT Committe...
2    Akhil Yadav Polemaina\nHyderabad, Telangana - ...
3    Alok Khandai\nOperational Analyst (SQL DBA) En...
4    Ananya Chavan\nlecturer - oracle tutorials\n\n...
..                                                 ...
215  Mansi Thanki\nStudent\n\nJamnagar, Gujarat - E...
216  Anil Kumar\nMicrosoft Azure (Basic Management)...
217  Siddharth Choudhary\nMicrosoft Office Suite - ...
218  Valarmathi Dhandapani\nInvestment Banking Oper...
219  Pradeep Kumar\nSecurity Analyst in Infosys - C...

                                            annotation  extras
0    [{'label': ['Skills'], 'points': [{'start': 12...     NaN
1    [{'label': ['Email Address'], 'points': [{'sta...     NaN
2    [{'label': ['Skills'], 'points': [{'start': 37...     NaN
3    [{'label': ['Skills'], 'points': [{'start': 80...     NaN
4    [{'label': ['Degree'], 'points': [{'start': 20...     NaN
..                                                 ...     ...
215  [{'label': ['College Name'], 'points': [{'star...     NaN
216  [{'label': ['Location'], 'points': [{'start': ...     NaN
217  [{'label': ['Skills'], 'points': [{'start': 78...     NaN
218  [{'label': ['Skills'], 'points': [{'start': 92...     NaN
219  [{'label': ['Skills'], 'points': [{'start': 58...     NaN

[220 rows x 3 columns]>

In [177]:
df = df.rename(columns={
    "text": "content",
    "label": "annotation"
})

In [178]:
df= df[['content', 'annotation']]
df

,content,annotation
0,Abhishek Jha\nApplication Development Associat...,"[{'label': ['Skills'], 'points': [{'start': 12..."
1,Afreen Jamadar\nActive member of IIIT Committe...,"[{'label': ['Email Address'], 'points': [{'sta..."
2,"Akhil Yadav Polemaina\nHyderabad, Telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37..."
3,Alok Khandai\nOperational Analyst (SQL DBA) En...,"[{'label': ['Skills'], 'points': [{'start': 80..."
4,Ananya Chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20..."
...,...,...
215,"Mansi Thanki\nStudent\n\nJamnagar, Gujarat - E...","[{'label': ['College Name'], 'points': [{'star..."
216,Anil Kumar\nMicrosoft Azure (Basic Management)...,"[{'label': ['Location'], 'points': [{'start': ..."
217,Siddharth Choudhary\nMicrosoft Office Suite - ...,"[{'label': ['Skills'], 'points': [{'start': 78..."
218,Valarmathi Dhandapani\nInvestment Banking Oper...,"[{'label': ['Skills'], 'points': [{'start': 92..."
219,Pradeep Kumar\nSecurity Analyst in Infosys - C...,"[{'label': ['Skills'], 'points': [{'start': 58..."

In [180]:


df.columns = df.columns.str.strip()
df.columns

# adjust here based on your dataset
df = df.rename(columns={
    "text": "content",
    "label": "annotation"
})

df = df[['content', 'annotation']].dropna()

In [181]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [182]:
def clean_text(text):
    text = str(text).lower()

In [183]:
text = re.sub(r'http\S+|www\S+', '', text)
text = re.sub(r'[^a-zA-Z]', ' ', text)

In [184]:
words = text.split()
words

['Pradeep',
 'Kumar',
 'Security',
 'Analyst',
 'in',
 'Infosys',
 'Career',
 'Contour',
 'Hyderabad',
 'Telangana',
 'Telangana',
 'Email',
 'me',
 'on',
 'Indeed',
 'indeed',
 'com',
 'r',
 'Pradeep',
 'Kumar',
 'eadd',
 'WORK',
 'EXPERIENCE',
 'Security',
 'Analyst',
 'in',
 'Infosys',
 'Career',
 'Contour',
 'March',
 'to',
 'Present',
 'Security',
 'incident',
 'and',
 'event',
 'management',
 'SIEM',
 'is',
 'the',
 'process',
 'of',
 'identifying',
 'monitoring',
 'and',
 'analysing',
 'security',
 'events',
 'or',
 'incidents',
 'within',
 'a',
 'real',
 'time',
 'IT',
 'environment',
 'It',
 'provides',
 'centralized',
 'view',
 'of',
 'the',
 'security',
 'scenario',
 'of',
 'an',
 'IT',
 'infrastructure',
 'EDUCATION',
 'B',
 'Tech',
 'Jawaharlal',
 'Nehru',
 'Technological',
 'University',
 'Hyderabad',
 'Telangana',
 'SKILLS',
 'Splunk',
 'Network',
 'Security',
 'Arc',
 'sight',
 'years',
 'SIEM',
 'years',
 'McAfee',
 'ESM',
 'year',
 'ADDITIONAL',
 'INFORMATION',
 'Technologies',
 'McAfee',
 'SIEM',
 'Arc',
 'sight',
 'HP',
 'Service',
 'manager',
 'Description',
 'Security',
 'incident',
 'and',
 'event',
 'management',
 'SIEM',
 'is',
 'the',
 'process',
 'of',
 'identifying',
 'monitoring',
 'and',
 'analysing',
 'security',
 'events',
 'or',
 'incidents',
 'within',
 'a',
 'real',
 'time',
 'IT',
 'environment',
 'It',
 'provides',
 'centralized',
 'view',
 'of',
 'the',
 'security',
 'scenario',
 'of',
 'an',
 'IT',
 'infrastructure',
 'Roles',
 'and',
 'Responsibilities',
 'Have',
 'Experience',
 'in',
 'device',
 'integration',
 'alarm',
 'creation',
 'in',
 'ESM',
 'Having',
 'Experience',
 'on',
 'analysing',
 'FIREWALL',
 'events',
 'Checking',
 'health',
 'status',
 'for',
 'all',
 'devices',
 'in',
 'ESM',
 'Working',
 'in',
 'Offshore',
 'SOC',
 'team',
 'Monitoring',
 'of',
 'SOC',
 'events',
 'detecting',
 'and',
 'preventing',
 'the',
 'Intrusion',
 'attempts',
 'Hands',
 'on',
 'experience',
 'monitoring',
 'the',
 'SIEM',
 'tool',
 'Provide',
 'level',
 'supports',
 'to',
 'manage',
 'SIEM',
 'components',
 'Creating',
 'reports',
 'as',
 'per',
 'client',
 'requirement',
 'Analysing',
 'daily',
 'weekly',
 'and',
 'monthly',
 'reports',
 'Creating',
 'case',
 'for',
 'the',
 'suspicious',
 'issue',
 'and',
 'forwarding',
 'it',
 'to',
 'Onsite',
 'SOC',
 'team',
 'for',
 'further',
 'investigation',
 'Monitoring',
 'the',
 'events',
 'on',
 'SIEM',
 'tool',
 'Creating',
 'the',
 'tickets',
 'in',
 'ticketing',
 'tool',
 'Finding',
 'false',
 'positive',
 'fine',
 'tuning',
 'and',
 'escalating',
 'Security',
 'events']

In [175]:
def clean_text(text):

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

In [185]:
df['content'] = df['content'].apply(clean_text)
df['content']

0      None
1      None
2      None
3      None
4      None
       ...
215    None
216    None
217    None
218    None
219    None
Name: content, Length: 220, dtype: object

In [186]:
tfidf = TfidfVectorizer(max_features=5000)

X_vectorized = tfidf.fit_transform(X)

In [187]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

In [188]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [189]:
y_pred = model.predict(X_test)
y_pred

array(['Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills', 'Skills', 'Skills', 'Skills', 'Skills',
       'Skills', 'Skills'], dtype='<U19')

In [190]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.6136363636363636

In [191]:
pickle.dump(model, open("model.pkl", "wb"))

pickle.dump(tfidf, open("tfidf.pkl", "wb"))

print("Model Saved Successfully")

Model Saved Successfully